data_ingestion:
  test_size: 0.2

feature_engineering:
  max_features: 50

model_building:
  learning_rate: 0.01
  n_estimators: 100
  random_state: 2
  cv_folds: 5

model_evaluation:
  scoring_metric: "accuracy"
  threshold: 0.5
